apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    policy.open-cluster-management.io/categories: ''
    policy.open-cluster-management.io/controls: ''
    policy.open-cluster-management.io/standards: ''
  managedFields:
    - apiVersion: policy.open-cluster-management.io/v1
      manager: unknown
      operation: Update
    - apiVersion: policy.open-cluster-management.io/v1
      manager: governance-policy-propagator
      operation: Update
  name: serverless-installed
  namespace: hive
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: serverless-operator-subscription
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: serverless-operator
                  namespace: openshift-operators
                spec:
                  installPlanApproval: Automatic
                  name: serverless-operator
                  source: redhat-operators
                  sourceNamespace: openshift-marketplace
            - complianceType: musthave
              objectDefinition:
                kind: Project
                apiVersion: project.openshift.io/v1
                metadata:
                  name: knative-serving
                  spec: {}
            - complianceType: musthave
              objectDefinition:
                kind: Project
                apiVersion: project.openshift.io/v1
                metadata:
                  name: knative-eventing
                spec: {}
            - complianceType: musthave
              objectDefinition:
                apiVersion: operator.knative.dev/v1alpha1
                kind: KnativeServing
                metadata:
                  name: knative-serving
                  namespace: knative-serving
                spec: {}
            - complianceType: musthave
              objectDefinition:
                apiVersion: operator.knative.dev/v1alpha1
                kind: KnativeEventing
                metadata:
                  name: knative-eventing
                  namespace: knative-eventing
                spec: {}
          remediationAction: enforce
          severity: high
  remediationAction: enforce
  placement:
    - placementBinding: binding-serverless-installed
      placementRule: placement-serverless-installed
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  managedFields:
    - apiVersion: policy.open-cluster-management.io/v1
      operation: Update
  name: binding-serverless-installed
  namespace: hive
placementRef:
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
  name: placement-serverless-installed
subjects:
  - apiGroup: policy.open-cluster-management.io
    kind: Policy
    name: serverless-installed
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  generation: 1
  managedFields:
    - apiVersion: apps.open-cluster-management.io/v1
      manager: multicluster-operators-placementrule
      operation: Update
    - apiVersion: apps.open-cluster-management.io/v1
      manager: unknown
      operation: Update
  name: placement-serverless-installed
  namespace: hive
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: vendor
        operator: In
        values:
          - OpenShift

